### ISSUE TITLE
[iam] url is being used as iam_url

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/node-sdk#731] opened 2018-06-27 13:24 UTC
Somehow the `url` is being used as `iam_url`

SDK Version: 3.5.1

## Steps to reproduce

1. Create a service instance in Sydney
1. Execute this code
    ```js
    let assistantService = new AssistantV1({
      version: '2018-02-16',
      url: 'https://gateway-syd.watsonplatform.net/assistant/api',
      iam_apikey: '0adu5bk5RDQQqnWtasdfmST0dJlAnZv-MeOi5R6b85eH'
    });
    assistantService.listWorkspaces((err, res) => console.log(err, res));
    ```
1. Output
    ```
    REQUEST { url: ’https://gateway-syd.watsonplatform.net/assistant/api',
    method: ‘POST’,
    headers:
      { ‘Content-type’: ‘application/x-www-form-urlencoded’,
        Authorization: ‘Basic Yng6Yng=’,
        ‘User-Agent’: ‘watson-developer-cloud-nodejs-3.5.1;’ },
    form:
      { grant_type: ‘urn:ibm:params:oauth:grant-type:apikey’,
        apikey: ‘0adu5bk5RDQQqnWtasdfmST0dJlAnZv-MeOi5R6b85eH’,
        response_type: ‘cloud_iam’ },
    gzip: true,
    callback: [Function] }
    REQUEST make request https://gateway-syd.watsonplatform.net/assistant/api
    REQUEST onRequestResponse https://gateway-syd.watsonplatform.net/assistant/api 301 { date: ‘Wed, 27 Jun 2018 00:12:40 GMT’,
    ‘content-type’: ‘text/html’,
    ‘content-length’: ‘178’,
    location: ‘https://gateway-syd.watsonplatform.net/assistant/api/’,
    connection: ‘close’,
    ‘x-global-transaction-id’: ‘6d3652a3c761d97a5fd2144c6955f596’,
    ‘x-dp-watson-tran-id’: ‘6d3652a3c761d97a5fd2144c6955f596’ }
    REQUEST redirect https://gateway-syd.watsonplatform.net/assistant/api/
    REQUEST reading response’s body
    REQUEST finish init function https://gateway-syd.watsonplatform.net/assistant/api
    REQUEST response end https://gateway-syd.watsonplatform.net/assistant/api 301 { date: ‘Wed, 27 Jun 2018 00:12:40 GMT’,
    ‘content-type’: ‘text/html’,
    ‘content-length’: ‘178’,
    location: ‘https://gateway-syd.watsonplatform.net/assistant/api/’,
    connection: ‘close’,
    ‘x-global-transaction-id’: ‘6d3652a3c761d97a5fd2144c6955f596’,
    ‘x-dp-watson-tran-id’: ‘6d3652a3c761d97a5fd2144c6955f596’ }
    REQUEST end event https://gateway-syd.watsonplatform.net/assistant/api
    REQUEST has body https://gateway-syd.watsonplatform.net/assistant/api 178
    REQUEST emitting complete https://gateway-syd.watsonplatform.net/assistant/api
    {
    “code”: 301,
    “x-global-transaction-id”: “6d3652a3c761d97a5fd2144c6955f596”
    }
    ```
The fix is to specify the `iam_url` which should not be the case
```js
let assistantService = new AssistantV1({
  version: '2018-02-16',
  url: 'https://gateway-syd.watsonplatform.net/assistant/api',
  iam_apikey: '0adu5bk5RDQQqnWtasdfmST0dJlAnZv-MeOi5R6b85eH',
  iam_url: 'https://iam.bluemix.net/identity/token'
});
assistantService.listWorkspaces((err, res) => console.log(err, res));
```

## Acceptance criteria
 - [ ] The default `iam_url` is used when it's not specified by the user

**Comment by dpopp07** [comment] 2018-07-17 21:30
@germanattanasio is this still affecting you? I cannot reproduce the bug. If not, I will close the issue.

**Closed** 2018-08-27 18:57 UTC
Labels: bug
