### ISSUE TITLE
[Discovery] History sequence causing valid requests to fail with empty Error

### ISSUE THREAD

**Issue by alex-thewsey-ibm** [watson-developer-cloud/node-sdk#688] opened 2018-05-04 15:36 UTC
**Bug**
Node v8.10.0
SDK v3.4.1
Relating to IBM Cloud support ticket CS0031363

**Context:** Performing (quite long) natural language queries with filters to find documents with similar text. Requesting a small subset of fields returned, for up to 100 documents. Our system makes quite rapid sequences of queries, but always in serial - one at a time.

### Expected Behaviour
A query which is valid through the API is valid through the Node SDK. Validity of queries is not affected by the order in which queries are performed.

### Actual Behaviour
Depending on the sequence in which queries are executed, we see `Error`s with no message: caused by the SDK receiving HTTP 400 from the service with no response body.

The errors are deterministic: Repeating a particular sequence of queries always fails at the same point. Retrying the query does not cause it to succeed. Giving a dummy NLQ like "Please start behaving" before retrying does not cause the failed query to succeed. The dummy query succeeds (returns 0 results).

By instrumenting `requestwrapper.js`, we've been able to demonstrate exactly the same query parameters succeeding in one run and failing in another. The only difference between the failed and successful request is the `Watson-DPAT` cookie. Example request JSONs are attached to the IBM Cloud support ticket.

We've looked at a wide range of options regarding the query itself: changes to document format; removing special characters from the NLQ (which can contain emojis, punctuation, newlines and other novelty whitespace)... But the fact that the same query succeeds in some cases suggests there's some kind of stateful stuff going wrong rather than an issue with the query or the collection.

Using the attached shim (replacing SDK `query()` with a simple `request`-based adapter) we've been able to run all sequences with no errors. We've been working with the WDS team to understand whether this might be a service or SDK issue, and are now raising this ticket at their request.

### Steps to Reproduce

We don't yet have a non-proprietary data & query set to share on GitHub, but could share examples with IBM support teams. This is not a rare error that we imagine much difficulty reproducing: we see test suites where e.g. ~50% of queries fail.

### Solution Ideas

- Watson-DPAT cookie is the only difference between failing & successful requests: Perhaps session management somewhere is causing an issue
- The error is less common on query sequences with a lot of commonality from one query to the next (iteratively extending the query & checking results) than on very different queries
- Seems like a very integration-y issue... I think it will require support from WDS team to resolve

[DiscoveryShim.js.txt](https://github.com/watson-developer-cloud/node-sdk/files/1975009/DiscoveryShim.js.txt)

**Comment by germanattanasio** [comment] 2018-05-04 21:11
We use the `Watson-DPAT` cookie to store the session in the request module so that subsequent requests don't have to use the `Authorization` header to authorize the request.

If we don't use cookies then each request will take an additional ~200ms because we will have to use the `username` and `password` to authenticate it.

I think the problem is on the server trying to use the cookie to authenticate the request. 

Can you try removing `request.jar()` from the `base_service.js`? if that fixes the issue then we can put an option in the constructor to ignore cookies for now.

**Comment by alex-thewsey-ibm** [comment] 2018-05-09 08:59
Thanks for the info @germanattanasio!

Yes I can confirm removing `_options.jar = request.jar();` from `base_service.js` fixes the issue

**Comment by germanattanasio** [comment] 2018-05-14 19:39
@anweshan can you take a look at this?

**Comment by germanattanasio** [comment] 2018-05-29 15:20
Related to https://github.com/watson-developer-cloud/node-sdk/issues/683

**Comment by germanattanasio** [comment] 2018-05-29 15:21
and https://github.com/watson-developer-cloud/node-sdk/issues/698

**Comment by germanattanasio** [comment] 2018-06-18 18:37
@alex-thewsey-ibm I think that this problem will be fixed once you switch to use an IAM instance where you will get an `apikey` rather than `username` and `password` and we won't be using the cookie to authorize the request

**Comment by dpopp07** [comment] 2018-10-08 16:40
@germanattanasio I believe the plan is to drop support for cookies in the next major release, so this issue can probably be closed. Can you confirm that?

**Comment by germanattanasio** [comment] 2018-11-18 21:50
This will get closed once we moved to 4.0

**Comment by dpopp07** [comment] 2019-08-01 22:15
Closing as 4.0 was released and cookies have been removed. If issues persist, this issue should be re-opened

**Closed by dpopp07** 2019-08-01 22:15 UTC
Labels: bug, service
