### ISSUE TITLE
createSession from Assistant V2 is not working behind http proxy

### ISSUE THREAD

**Issue by ChristianStornowski** [watson-developer-cloud/node-sdk#900] opened 2019-07-03 16:01 UTC
**Overview**
My enterprise is using a http proxy and because of that `createSession` from `ibm-watson/assistant/v2` is not working. Internally a token from https://iam.cloud.ibm.com/identity/token is created with an axios https post call.
I think axios is not working with https post calls and http proxy.

**Expected behavior**
```
{
  "session_id": "XXX-XXXX-XXXX-XXX-XXXX."
}
```

**Actual behavior**
```
Error: Response not received. Body of error is HTTP ClientRequest object
    at RequestWrapper.formatError (XXX\watson\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:232:21)
    at XXX\watson\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:220:29
    at processTicksAndRejections (internal/process/task_queues.js:82:5) {

```

**How to reproduce**
Use a http proxy and execute this code:

```
const AssistantV2 = require('ibm-watson/assistant/v2'); // watson sdk

const assistant = new AssistantV2({
    version: '2019-06-14',
    iam_apikey: XYZ',
    url: 'https://XXX.watsonplatform.net/assistant/api',
    headers: {
        'X-Watson-Learning-Opt-Out': 'true'
    }
});

assistant.createSession({
    assistant_id: 'XXX-XXX-XXX-XXX'
})
    .then(res => {
        console.log(JSON.stringify(res, null, 2));
    })
    .catch(err => {
        console.log(err);
    });
```

**SDK Version**
4.2.1

**Additional information:**
- OS: Windows 10
- nodejs: 12.5.0

**Additional context**
I found this homepage: https://janmolak.com/node-js-axios-behind-corporate-proxies-8b17a6f31f9d and added this code in `requestwrapper.js`:

   ```
    var tunnel = require("tunnel");

        var agent = tunnel.httpsOverHttp({
            proxy: {
                host: 'XXX.materna.de',
                port: YYYY,
            },
        });

        axiosConfig.httpsAgent = agent;
        axiosConfig.proxy = false;

        this.axiosInstance = axios_1.default.create(axiosConfig);
```
 After this everything is working.

**Comment by dpopp07** [comment] 2019-07-04 18:43
> After this everything is working.

So are you still having an issue?

I was going to suggest using the [`axios` configuration options](https://github.com/axios/axios#request-config), which are exposed in the **constructor** of the service object. That is the only way to use proxies with the SDK

**Comment by ChristianStornowski** [comment] 2019-07-05 05:25
I don't have this issue with my a workaround. But i'm manipulating a 3rd party library and this could be dangerous. So i don't really like this workaround. ;-)
The Java SDK has an option for proxies.

**Comment by S-hiyuko** [comment] 2019-07-08 05:52
Dear Christian Stornowski,

Hi,I face same issue in Assistant V1.
I tried to add your code in requestwrapper.js,but not working. Could you teach me...

1.Where are you add the code in requestwrapper.js? 
2.What is "axiosConfig" parameter?  Did you difine the parameter yourself?

**Comment by ChristianStornowski** [comment] 2019-07-08 07:07
Dear S-hiyuko,

I opened the file node_modules/ibm-cloud-sdk-core/lib/requestwrapper.js, searched for axios_1.default.create and added my code.
Because of `var tunnel = require("tunnel");` I added tunnel as a npm dependency and installed it.
This file is attached at this comment.
[requestwrapper.zip](https://github.com/watson-developer-cloud/node-sdk/files/3367026/requestwrapper.zip)

`axiosConfig` itself is already present. I only added 2 properties.

[patch-package]( https://www.npmjs.com/package/patch-package) is a good way to persist this changes without overriding `requestwrapper.js` manually.

**Comment by S-hiyuko** [comment] 2019-07-08 08:47
Dear Christian Stornowski,

Thank you very match for your cooperation!!

Our application is working after installing same version node.js and SDK, and putting your requestwrapper.js.

Thank you so, so much!

**Comment by dpopp07** [comment] 2019-07-08 14:49
@ChristianStornowski @S-hiyuko You should be able to do this without altering `requestwrapper.js` - the SDK is written so that you can configure these parameters at the service level. All of the `axios` config properties are exposed in the service constructor:

```js
const assistant = new AssistantV1({
  iam_apikey: 'your-api-key',
  // other params...
  proxy: '<some proxy config>',
  httpsAgent: '<or some https agent config>'
});
```

These will get passed down to the `axios` config object by the SDK.

**Comment by ChristianStornowski** [comment] 2019-07-08 14:58
It's not working with AssistantV2.

```
var agent = tunnel.httpsOverHttp({
    proxy: {
        host: 'XXX.materna.de',
        port: YYYY,
    },
});

const assistant = new AssistantV2({
    version: '2019-06-14',
    iam_apikey: AAA',
    url: 'ZZZ',
    headers: {
        'X-Watson-Learning-Opt-Out': 'true'
    },
    httpsAgent: agent,
    proxy: false
});
```

**Comment by dpopp07** [comment] 2019-07-08 15:44
Okay, I just confirmed that the constructor does in fact set those config options for the request to the service but not for the IAM token request. Are you using `iam_apikey` for authentication? That could certainly be the problem.

I can look into fixing that soon but could you confirm that this is the case by trying to using an `iam_access_token` that you've created and seeing if that works?

**Comment by S-hiyuko** [comment] 2019-07-09 02:42
It's not working V1 too. So please also fix it in V1.
We do not use iam_access_token.

**Comment by ChristianStornowski** [comment] 2019-07-09 08:52
@dpopp07

I used this documentation to generate a token: https://cloud.ibm.com/docs/services/watson?topic=watson-iam.
After getting a token I used iam_access_token to configure, removed iam_apikey property, my `AssistantV2`. But it's still not working without my workaround.

**Comment by dpopp07** [comment] 2019-08-01 15:44
@ChristianStornowski Sorry I haven't responded in a bit. I am actively working on this issue this week. The problem is, I am having trouble recreating the issue because I am not behind a forced proxy.

The best I've been able to do so far is set up an HTTP proxy and try to run HTTPS requests through it to Watson. I am unable to do this using the `proxy` parameter, but I am able to do it successfully with your workaround.

That said, when I pass the agent and proxy through the constructor it still works for me. I have no idea why it wouldn't work for you. If you look at the code, the variables are passed from the constructor to the `axiosConfig` object that's used to create the `axiosInstance`. There shouldn't be any difference.

Will you share your specific error that you are getting when you do that?

In the meantime, I can push a branch for you to test with that shares the axios config with the token manager so that IAM requests can also be configured from the constructor.

For reference, I am able to run through the HTTP proxy using this config:
```js
const assistant = new AssistantV1({
  iam_access_token: '<my token>',
  version: '<version>',
  httpsAgent: tunnel.httpsOverHttp({
    host: '1.2.3.4',
    port: 1234,
  }),
  proxy: false,
});
```

**Comment by ChristianStornowski** [comment] 2019-08-05 15:33
This is my new configuration:
```
var tunnel = require("tunnel");

const assistant = new AssistantV2({
    version: '2019-06-14',
    iam_apikey: 'xyz',
    url: 'https://gateway-fra.watsonplatform.net/assistant/api',
    headers: {
        'X-Watson-Learning-Opt-Out': 'true'
    },
    httpsAgent:  tunnel.httpsOverHttp({
        proxy: {
            host: 'xyz.abc.de',
            port: 8080,
        },
    }),
    proxy: false
});
```

I'm getting the some error:

```
Error: Response not received. Body of error is HTTP ClientRequest object
    at RequestWrapper.formatError (C:\Users\cstornow\IdeaProjects\watson\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:232:21)
    at C:\Users\cstornow\IdeaProjects\watson\node_modules\ibm-cloud-sdk-core\lib\requestwrapper.js:220:29
    at processTicksAndRejections (internal/process/task_queues.js:85:5) {
```

**Comment by dpopp07** [comment] 2019-08-05 15:42
@ChristianStornowski Thanks for sharing. Since I can't reproduce this locally, I put together a branch with a potential fix for you to try.

Would you be open to pulling down [this test branch](https://github.com/watson-developer-cloud/node-sdk/tree/proxy-test-share-axios-config), and trying to run your code, using the same configuration, with that local version of the SDK?

What I did in that branch is share the `axios` instance with the token manager so that all outgoing requests use the same options - this should propagate the `httpsAgent` and `proxy` values to all requests and hopefully solve your issue.

Please let me know if you are able to try this out and if so, what your results are. Thanks

**Comment by dpopp07** [comment] 2019-08-07 14:47
@ChristianStornowski @S-hiyuko will y'all try the [potential fix](https://github.com/watson-developer-cloud/node-sdk/tree/proxy-test-share-axios-config) I posted and let me know what your results are?

**Comment by ChristianStornowski** [comment] 2019-08-07 14:49
@dpopp07 i will try your potential fix as soon as possible. :-)

**Comment by ChristianStornowski** [comment] 2019-08-07 16:08
I followed the readme.md and everything is working for this DiscoveryV1 version.
I used the current released version from DiscoveryV1 for the current released from ibm-watson and it's not working.
So everything looks good with this branch. :-)

**Comment by dpopp07** [comment] 2019-08-07 16:29
Great! Thanks a bunch for trying that out. It seems that that configuring `axios` worked fine but we were not propagating that config to all requests, which caused the problem. I will post that fix today, should be released today or tomorrow.

**Comment by dpopp07** [comment] 2019-08-07 22:05
Should be fixed in #928

**Comment by dpopp07** [comment] 2019-08-08 13:41
@ChristianStornowski @S-hiyuko will you confirm everything is working in `v4.3.2` using [the approach described here](https://github.com/watson-developer-cloud/node-sdk#using-the-sdk-behind-a-corporate-proxy)?

**Comment by ChristianStornowski** [comment] 2019-08-09 06:01
From my side everything is fine with v4.3.2. :-)

**Comment by dpopp07** [comment] 2019-08-09 14:03
Excellent! Thanks again for your help there

Closing this issue - @S-hiyuko if this does not fix your problem, please re-open the issue

**Closed by dpopp07** 2019-08-09 14:03 UTC
Labels: bug

**Comment by S-hiyuko** [comment] 2019-08-13 04:25
@dpopp07 
Hi,
I try it, but it is not working in V4.3.2. My code is bellow.

————————————
var AssistantV1 = require('ibm-watson/assistant/v1');
var tunnel = require('tunnel');

// Create the service wrapper
module.exports.assistant = new AssistantV1({
    version: env.bluemix.assistant.version,
    iam_apikey: env.bluemix.assistant.iam_apikey,
    url: <assistant.url>,
    httpsAgent: tunnel.httpsOverHttp({
      host: <proxy.url>,
      port: <proxy.port>
    }),
    proxy: false,
  });
———————————
I understand that  I need to set proxy url in “host” section and port in “port” section. Is it correct?
In README, there are no section of setting assistant url, so I set it “url” section. Is it correct?

**Comment by dpopp07** [comment] 2019-08-13 14:13
> I need to set proxy url in “host” section and port in “port” section. Is it correct?
> I set it in “url” section. Is it correct?

Yes, those are correct.

What specific error are you getting?

**Comment by Samer2** [comment] 2019-09-17 03:05
Hi @dpopp07 I'm getting the same error when I pull ibm-watson module behind nexus repo. i tried the proxy example given in #944 but no luck. 
Node version: 10.16.3 npm: 6.9.4 

{ Error: Response not received. Body of error is HTTP ClientRequest object
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT     at RequestWrapper.formatError (/home/vcap/deps/0/node_modules/ibm-cloud-sdk-core/lib/requestwrapper.js:218:21)
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT     at /home/vcap/deps/0/node_modules/ibm-cloud-sdk-core/lib/requestwrapper.js:206:29
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT     at process._tickCallback (internal/process/next_tick.js:68:7)
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT   message:
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT    'Response not received. Body of error is HTTP ClientRequest object',
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT   body:
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT    Writable {
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT      _writableState:
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT       WritableState {
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         objectMode: false,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         highWaterMark: 16384,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         finalCalled: false,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         needDrain: false,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         ending: false,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         ended: false,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         finished: false,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         destroyed: false,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         decodeStrings: true,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         defaultEncoding: 'utf8',
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         length: 0,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         writing: false,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         corked: 0,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         sync: true,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         bufferProcessing: false,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         onwrite: [Function: bound onwrite],
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         writecb: null,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         writelen: 0,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         bufferedRequest: null,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         lastBufferedRequest: null,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         pendingcb: 0,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         prefinished: false,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         errorEmitted: false,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         emitClose: true,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         autoDestroy: false,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         bufferedRequestCount: 0,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         corkedRequestsFree: [Object] },
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT      writable: true,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT      _events:
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT       [Object: null prototype] {
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         response: [Function: handleResponse],
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         error: [Function: handleRequestError] },
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT      _eventsCount: 2,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT      _maxListeners: undefined,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT      _options:
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT       { protocol: 'https:',
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         maxRedirects: 21,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         maxBodyLength: Infinity,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         path: '/identity/token',
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         method: 'post',
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         headers: [Object],
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         agent: [Agent],
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         auth: undefined,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         hostname: 'iam.cloud.ibm.com',
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         port: null,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         nativeProtocols: [Object],
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         pathname: '/identity/token' },
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT      _redirectCount: 0,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT      _redirects: [],
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT      _requestBodyLength: 135,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT      _requestBodyBuffers: [ [Object] ],
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT      _onNativeResponse: [Function],
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT      _currentRequest:
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT       ClientRequest {
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         _events: [Object],
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         _eventsCount: 6,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         _maxListeners: undefined,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         output: [],
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         outputEncodings: [],
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         outputCallbacks: [],
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         outputSize: 0,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         writable: true,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         _last: true,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         chunkedEncoding: false,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         shouldKeepAlive: false,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         useChunkedEncodingByDefault: true,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         sendDate: false,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         _removedConnection: false,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         _removedContLen: false,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         _removedTE: false,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         _contentLength: null,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         _hasBody: true,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         _trailer: '',
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         finished: false,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         _headerSent: true,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         socket: [TLSSocket],
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         connection: [TLSSocket],
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         _header:
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT          'POST /identity/token HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/x-www-form-urlencoded\r\nAuthorization: Basic Yng6Yng=\r\nUser-Agent: axios/0.18.1\r\nContent-Length: 135\r\nHost: iam.cloud.ibm.com\r\nConnection: close\r\n\r\n',
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         _onPendingData: [Function: noopPendingOutput],
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         agent: [Agent],
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         socketPath: undefined,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         timeout: undefined,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         method: 'POST',
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         path: '/identity/token',
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         _ended: false,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         res: null,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         aborted: undefined,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         timeoutCb: null,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         upgradeOrConnect: false,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         parser: null,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         maxHeadersCount: null,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         _redirectable: [Circular],
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         [Symbol(isCorked)]: false,
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT         [Symbol(outHeadersKey)]: [Object] },
   2019-09-16T22:52:22.25-0400 [APP/PROC/WEB/0] OUT      _currentUrl: 'https://iam.cloud.ibm.com/identity/token' } }
