### ISSUE TITLE
[Alchemy API] Returns Invalid JSON with \u Unicode Escapes

### ISSUE THREAD

**Issue by kfitzgerald** [watson-developer-cloud/node-sdk#478] opened 2017-07-14 21:03 UTC
From time to time, AlchemyAPI will spit back invalid JSON, with some string values containing literal \u escape expressions.

For example:
```js
    {
      "relevance": "0.529379",
      "text": "\u0007SOCIAL SECURITY"
    },
```

And as a result, when https://github.com/watson-developer-cloud/node-sdk/blob/master/lib/requestwrapper.js#L67 tries to JSON.parse, the error is silently eaten:
```js
    try {
      body = JSON.parse(body);
    } catch (e) {
      // if it fails, just return the body as a string
    }
```

Worse yet, since there is no error, the response formatter makes a mess out of everything: https://github.com/watson-developer-cloud/node-sdk/blob/master/lib/alchemy_error_formatter.js
```js
      if (result.status !== ‘OK’) {
        err = new Error(result.statusInfo || response[‘headers’][‘x-alchemyapi-error-msg’]);
        err.code = 400;
        err.body = result;
        extend(err, result);
        result = null;
      }
```
Since `result` is actually the string body of the response, `string.status` will of course be `undefined`, so the error clause fires.

`err.message` will be empty, since `result.statusInfo` is obviously undefined, and the request technically did not fail, so there was no alchemy error header.

And the cherry on top, is that since result is a string, when the `extend(err, result)` fires, every character of the string is added a property of `err`. For example:
```js
{
  "0": "{",
  "1": "\r",
  "2": "\n",
  "3": " ",
  "4": " ",
  "5": " ",
  "6": " ",
  "7": "\"",
  "8": "s",
  "9": "t",
  "10": "a",
  "11": "t",
  "12": "u",
  "13": "s",
  "14": "\"",
  "15": ":",
  "16": " ",
  "17": "\"",
  "18": "O",
  "19": "K",
  "20": "\"",
  "21": ",",
// ...
  "4134": "]",
  "4135": "\r",
  "4136": "\n",
  "4137": "}",
  "4138": "\r",
  "4139": "\n",
  "code": 400,
  "body": "{\r\n    \"status\": \"OK\",\r\n ... "
}
```

Regarding steps to reproduce, I can be privately contacted with a payload to use to consistently reproduce the error. 

Node: v6.11.0
SDK: v2.32.1

There are really two things going on here. First, the API is returning invalid JSON JavaScript cannot parse. Second, the SDK doesn't handle this case gracefully, and instead produces wild error messages that are extremely difficult to deal with. In theory, it's not the SDK's job to deal with the API returning garbage json, but it *should not* be allowed to make crazy errors that extend strings.

Thoughts on how to deal with this?

Thanks,
-Kevin

**Comment by nfriedly** [comment] 2017-07-17 14:58
Ugh, you're right on both counts.


I'll talk to the AlchemyAPI team about avoiding invalid JSON output in the first place, but like you said, the SDK should handle this better.

It's been on my mind for a while to move the error parsing code (and, really, all of [requestwrapper.js](https://github.com/watson-developer-cloud/node-sdk/blob/master/lib/requestwrapper.js)) to the [base class](https://github.com/watson-developer-cloud/node-sdk/blob/master/lib/base_service.js), and then break it up into smaller parts so that individual classes could override it to work around cases like this.

My plate is pretty full right now; is this something that you'd be interested in doing and sending us a PR?

**Comment by nfriedly** [comment] 2017-07-17 15:06
Also can you email me the payload so that I can pass it along to the team? nfriedly@us.ibm.com

**Comment by kfitzgerald** [comment] 2017-07-17 17:31
@nfriedly payload sent! I'll see if I can hack something together. Might not be for a while since I got conscripted for jury duty today. 😬

**Comment by nfriedly** [comment] 2017-07-17 17:53
Good luck! We need smart people on juries!

**Comment by Decker87** [comment] 2017-07-18 16:10
Is that not valid JSON? When I throw

```
{
	"relevance": "0.529379",
	"text": "\u0007SOCIAL SECURITY"
}
```

at https://jsonlint.com/, it says it's valid. Is it a node-vs-other-languages thing?

**Comment by nfriedly** [comment] 2017-07-18 16:24
That's a fair point. My reading of [the spec](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) seems to indicate that it should be valid also. I suppose there may be a bug somewhere in the SDK (?)

**Comment by kfitzgerald** [comment] 2017-07-26 22:01
Awesome! It is totally safe to publish. Thanks @nfriedly !

**Comment by nfriedly** [comment] 2017-07-27 19:46
I finally tracked it down.. The `\u007` wasn't the issue, it was `\a` - which is invalid JSON. Here's a shorter example:

```sh
curl -X POST --data "extract=entity&text=Bear%20River%20Massacre%20ceremony%20marks%20sesquicentennial%20anniversary%20of%20event%20Farid%20Rushdi%07%20for%20the%20Journal&outputMode=json" "https://access.alchemyapi.com/calls/text/TextGetCombinedData?apikey=<api key here>"
```
```json
{
    "status": "OK",
    "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
    "language": "english",
    "entities": [
        {
            "type": "Person",
            "relevance": "0.33",
            "count": "1",
            "text": "Farid Rushdi\a"
        },
        {
            "type": "PrintMedia",
            "relevance": "0.33",
            "count": "1",
            "text": "Journal"
        },
        {
            "type": "GeographicFeature",
            "relevance": "0.33",
            "count": "1",
            "text": "Bear River",
            "disambiguated": {
                "subType": [
                    "Location",
                    "BodyOfWater",
                    "River"
                ],
                "name": "Bear River (Utah)",
                "dbpedia": "http://dbpedia.org/resource/Bear_River_(Utah)",
                "freebase": "http://rdf.freebase.com/ns/m.03658x",
                "yago": "http://yago-knowledge.org/resource/Bear_River_(Utah)"
            }
        }
    ]
}
```
That `\a` at the end of `"text": "Farid Rushdi\a"` is invalid. I'm talking to the API team again to get this fixed there.

**Comment by Decker87** [comment] 2017-07-27 20:20
Bug issue for us: https://github.ibm.com/watson-nlu/planning-hub/issues/847

And many thanks for giving us a repro case... we all know how hard it is to debug without one!

**Comment by nfriedly** [comment] 2017-07-27 20:34
I fixed the ugly error messages, or at least improved them anyways. We can leave this issue open until the root cause is fixed.

@Decker87 can you post an update here when the fix is released?

**Comment by idfah** [comment] 2017-10-30 19:10
@nfriedly this bug is now fixed in watson-nlu and will publicly available in a week or so.  We now return \u0007 instead of the \a bell character.  Same thing for vertical tabs.  Thanks for the report!

https://github.ibm.com/watson-nlu/planning-hub/issues/847

**Comment by nfriedly** [comment] 2017-10-30 19:35
Cool, thank you!

I'm going to go ahead and close this now.

**Closed by nfriedly** 2017-10-30 19:35 UTC
