### ISSUE TITLE
speech_to_text: "%HESITATION" placeholder in response

### ISSUE THREAD

**Issue by loretoparisi** [watson-developer-cloud/node-sdk#348] opened 2016-12-06 17:33 UTC
In the `speech_to_text` REST api endpoint we are getting this placeholder `%HESITATION`

```
[
                    "%HESITATION",
                    3.02,
                    3.52
                 ]
              ]
           },
           {
              "transcript": "I thought they have seen the school %HESITATION "
           },
           {
              "transcript": "I thought there have been these low %HESITATION "
```

that seems to refer to [this](https://developer.ibm.com/answers/questions/235600/hesitation-in-speech-to-text-response.html) issue.

**Comment by daniel-bolanos** [comment] 2016-12-06 18:00
Hi @loretoparisi those symbols mean that a filled pause was found, for example "hmm" or "mmm", etc. If you do not need them in you application you can just filter them out using a regular expression.

**Comment by nfriedly** [comment] 2016-12-06 19:38
I'm going to close this ticket for now, because this is the expected behavior of the service and not an SDK issue.

FWIW, the JS SDK (for browsers) has a format stream that replaces these with an ellipse (...). I have work in progress to make that also work smoothly with the Node SDK.

@daniel-bolanos are there any other symbols with special meanings? (I saw `~NS` and `~VP` now get [checked for in the demo](https://github.com/watson-developer-cloud/speech-to-text-nodejs/blob/bd2429dc3e1fd12cb38655ac7fba80cbeabd0bb6/src/views/displaymetadata.js#L848).) Do you think you could poke the documentation team to mention %HESITATION and any other symbols somewhere?

**Closed by nfriedly** 2016-12-06 19:38 UTC

**Comment by loretoparisi** [comment] 2016-12-07 08:22
@nfriedly @daniel-bolanos could you please point me to the docs where those symbols are defined as expected behaviors? I did not find any.

Thank you.

**Comment by jeffpk62** [comment] 2016-12-14 18:54
The documentation update that includes information about the `%HESITATION` marker is now available on the public site:  http://www.ibm.com/watson/developercloud/doc/speech-to-text/output.shtml#hesitation.  It was just released, so it needs to propagate across the servers and you may need to refresh the page.

**Comment by nfriedly** [comment] 2016-12-14 20:16
@jeffpk62 

> Other languages can use different markers; for example, Japanese uses the token D_

Could you list all of these in the docs?

**Comment by jeffpk62** [comment] 2016-12-15 22:24
I hope to, @nfriedly, but I need the Speech team to provide the information, which they have to get from the teams that generate the models.  I didn't want to wait for complete details to add the information to the documentation, since there were open issues against this, so we hand-wave for the moment.  I'll add the details for the other languages once I have them.
