### ISSUE TITLE
[speech-to-text] websocket recognize stream does not handle multiple "sessions" properly

### ISSUE THREAD

**Issue by frickenate** [watson-developer-cloud/node-sdk#487] opened 2017-07-29 07:29 UTC
**Node version**: 8.2.1
**SDK version**: 2.37.0

**Expected behavior**

A single websocket connection is designed, according to the documentation, to support multiple transcriptions with a single socket connection. The SDK needs to work properly in this situation, as the whole point of the websocket implementation is to reduce the need to close/reopen sockets.

**Steps to reproduce, Actual behavior**

You have the following code in `speech-to-text/recognize_stream.js` in the `socket.onmessage` function for when the server sends a `listening` message:

```js
if (data.state === 'listening') {
  // this is emitted both when the server is ready for audio, and after we send the close message to indicate that it's done processing
  if (!self.listening) {
    self.listening = true;
    self.emit('listening');
  } else {
    self.listening = false;
    socket.close();
  }
  recognized = true;
}
```

The `if/else` clause there completely prevents reusing the websocket connection for subsequent audio transcriptions. After my code does a `recognizer.emit('finish');` to send a `stop` message - or sends an empty buffer blob - to terminate the end of the current audio fragment, the server sends back a new `listening` message to indicate that another audio fragment is ready to be processed. But nothing in your code ever sets `self.listening = false` after successfully processing the first fragment, and so this conditional statement closes the socket! I don't understand why the `if/else` is there to begin with.

The code comment says "this is emitted both when the server is ready for audio, and **after we send the close message to indicate that it's done processing**" - except that a `close` message sent to the server is indicating to "close" the current audio transcription and then to listen for another - not to "close" the socket. The code works if I remove the `if` and `else` clauses, while leaving the contents inside the `if` block in place. I'm not sure if I'm missing something that would result in an edge-case bug elsewhere.

This block of code should be replaced by something along the lines of:

```js
// this is emitted when the server is ready for audio
if (data.state === 'listening') {
  self.listening = true;
  self.emit('listening');

  recognized = true;
}
```

Even with this working change, the tracking of the `self.listening` property remains sloppy.

**Comment by nfriedly** [comment] 2017-07-31 21:34
This is by design, as the current behavior meets most user's needs - transcribing a single file/audio stream and receiving an `end` event once it's complete. (After the `end` event, Node.js prevents streams from emitting any more `data` events.)

When transcribing multiple audio files/streams, the expected behavior is to create multiple connections.  

The main reason for using a WebSocket *here* is to allow the transcription to come back incrementally while the audio is being uploaded. With HTTP, this is awkward and requires multiple simultaneous connections.

Is there any reason that you need to use a single connection to process multiple segments of audio?

If you'd like to see an option to keep the socket open, please send a Pull Request. The default behavior of closing the socket at the end of the first transcription should remain intact though.

Note that  after a certain timeout, the service will automatically close sockets that aren't sending data.

Also note that https://github.com/watson-developer-cloud/speech-javascript-sdk/blob/master/speech-to-text/recognize-stream.js is a somewhat more up-to-date version of this file. In particular, because the service accepts and buffers audio from before the `{"state": "listening"}` message, it no longer waits to begin send audio. This results in less latency. Those changes will be merged here in the future, but are waiting until a major release because there are several breaking  changes.

**Comment by frickenate** [comment] 2017-07-31 23:08
Is this not the official library? I'm sorry to say you are simply mistaken. Read the documentation: https://www.ibm.com/watson/developercloud/doc/speech-to-text/websockets.html

You're confusing the `close` websocket message with the closing of a socket. They are not the same thing - "close" is just the name of the message, and has nothing to do with the socket. I've already tested, and the service works as intended: you send a `close` payload, receive the `final` results, receive another `listening` response, and then you are free to send more audio (or in fact, a new `start` payload to change the parameters, which is another thing this sdk doesn't support properly).

It's absurd and *wrong* (not a matter of opinion or an "edge case") to think that users should be closing the websocket after a single request. Please read the documentation; this sdk is non-compliant and throws away a large part of the benefits of using a websocket in the first place.

**Comment by nfriedly** [comment] 2017-08-01 15:27
I've read the documentation, and I understand the difference. Triggering the close (of everything) at the end of processing the source ReadableStream is the standard behavior of Node.js streams and, speaking from experience, the behavior that most users expect in a Node.js stream, even if it's not typical for a WebSocket.

You're the first person I'm aware of to request the behavior of keeping the WebSocket open after the first stream has been processed. That said, since the API supports this behavior, I do think it's reasonable to request that the SDK to support it as well. 

There are several caveats to this mode of usage that mainly boil down to it being more expensive: you must send some audio (even just silence) every 30 seconds to keep the connection open, and you pay for the processing of this audio. You must also set `inactivity_timeout` to `-1` to keep the session open indefinitely when sending silence.

I may not be able to get it implemented right away, but if you can send a PR with the change (and a test, please), I can release it fairly quickly. 

Lastly, please watch your tone, this is a place for friendly technical discussion.

**Closed** 2017-12-08 20:25 UTC
