### ISSUE TITLE
The library should support authenticating with token

### ISSUE THREAD

**Issue by jsstylos** [watson-developer-cloud/node-sdk#30] opened 2015-06-26 18:51 UTC
Developers should be able to create an instance of the service when they only have a token, not just a username and password.

**Comment by germanattanasio** [comment] 2015-10-11 02:06
if users specify only the `token`, what do we do after it expires?

**Comment by nfriedly** [comment] 2015-10-15 19:27
I think this is not a bad idea, but I want to punt it for v1.0.

Also, I think we should make several service-specific client-side libraries, and those should be token-only.

**Comment by nfriedly** [comment] 2016-03-07 22:08
I just tested this with the Dialog service and it actually worked. I'm going to check the other services and close this if I don't see any other issues.

**Comment by monte-hayward** [comment] 2016-03-17 20:19
@germanattanasio & @nfriedly ,
What is the expected life of an auth token?  

I wrote a refresh util that refreshes after 10 minutes. It worked for 38 minutes / 51 1-minute segments, then got `{"type": "error", "isTrusted": false, ...}`

**Comment by nfriedly** [comment] 2016-03-17 20:26
I believe it's 1 hour, but that error doesn't sound like an auth error. It sounds like something came up after the connection was established. Is it repeatable?

**Comment by monte-hayward** [comment] 2016-03-17 20:28
finding out now. 

by the way, it's insane to do 1 minute segments -- I'm only doing it to test my segment offset logic.

**Comment by monte-hayward** [comment] 2016-03-17 21:53
Tried to repro, and it died with the same error at 21 segments / 12 minutes runtime. I agree, that does not seem to be token-related.

I'm unclear on token parameter usage. 
Which one of these is correct?
(I am using the websocket endpoint).

```
// first create service, including username / password
  var s2t = watson.speech_to_text(credentials);
```

```
// for each audio segment
  // refresh token if needed, then which one of these?
  params.headers ['X-Watson-Authorization-Token'] = token;
  // or
  params ['X-Watson-Authorization-Token'] = token;
  // or
  params['watson-token'] = token;
  
  // then
  var rs = s2t.createRecognizeStream(params); // this opens a web socket
```

**Comment by nfriedly** [comment] 2016-03-17 21:58
I think either option would work: the X- one puts the token in a header while the watson-token option appends it to the querystring. You should only use one, not both.

For the error, do you know if it came before, during, or after audio transmission? Did the service send back any data before the error occurred?

**Comment by monte-hayward** [comment] 2016-03-18 18:43
> Did the service send back any data before the error occurred?
In the first instance, the service sent back 51 final results, in the second, 21.

**Comment by nfriedly** [comment] 2016-03-18 19:15
Aah, did you have interim_results disabled and a bunch of single-result files?

@daniel-bolanos any idea what's going on here?

**Comment by daniel-bolanos** [comment] 2016-03-18 19:25
Hello I do not understand what the issue is. "In the first instance, the service sent back 51 final results, in the second, 21" <- do you open the websocket and feed the same data and get different results?

do you get any error codes?

thank you

Dani

**Comment by nfriedly** [comment] 2016-03-18 19:30
@daniel-bolanos I believe he was processing a large number of small audio files, sequentially. Each one opens a new websocket. On the first attempt 50 files/websockets succeeded, and then the 51st failed. On the second attempt, it failed on the 21st file/websocket.

**Comment by daniel-bolanos** [comment] 2016-03-18 19:35
is this the error code he is getting? "{"type": "error", "isTrusted": false, ...}" ?
from the STT service?

**Comment by nfriedly** [comment] 2016-03-18 19:38
No, I think it's coming from the websocket client (the browser); they tend to give horribly unhelpful errors.

**Comment by daniel-bolanos** [comment] 2016-03-18 20:07
I see. To me this seems unrelated to the STT service. Could he use your javascript wrapper to build the browser based websocket client? or get inspiration from there? 

Dani

**Comment by nfriedly** [comment] 2016-03-18 20:25
I've seen that error before while working on the lib... but I can't seem to reproduce it now.

**Closed** 2016-07-29 15:45 UTC
Labels: enhancement
