### ISSUE TITLE
[speech-to-text] The same audio can got text before,Now is Error 1006 

### ISSUE THREAD

**Issue by JimZhang1028** [watson-developer-cloud/node-sdk#815] opened 2018-12-16 13:53 UTC
The same code that used to work is now returning an error code: 1006.
We have 5 audios and only the shortest one works
This problem started in 2018-11-19

When I use `curl` I get a response.
```sh
curl -X POST -u "username":"password" --header "Content-Type: audio/wav" \
--data-binary @./sound16000.wav \
"https://stream.watsonplatform.net/speech-to-text/api/v1/recognize?timestamps=true"
```

The Watson support team tested my service and they said it works fine.

This issue's SDK version.
 * Node: 6.12.3
 * SDK: 3.0.3

We use Visual Recognition and we need IAM so we updated the SDK version to `3.15.0`

I've attached the audio file([sound16000.zip](https://github.com/watson-developer-cloud/node-sdk/files/2683592/sound16000.zip)) to reproduce the error

**Comment by germanattanasio** [comment] 2018-12-17 20:45
@JimZhang1028 can you add the code you are using so that we can reproduce the problem?

**Comment by JimZhang1028** [comment] 2018-12-18 01:47
@germanattanasio 
Our system use watson-developer-cloud nodejs sdk for development. It normally works for 6 month，But suddenly the old video can not get text from STT(1/5 can success) from last month. So I write the code as below for test. All the parameter is the same as our system. (watson-developer-cloud version is 3.15.0)
```
var SpeechToTextV1 = require('watson-developer-cloud/speech-to-text/v1'); 
var fs = require('fs'); 
var STT = new SpeechToTextV1({ 
	username: 'my user name', 
	password: 'my password', 
	url: 'https://stream.watsonplatform.net/speech-to-text/api/' 
}); 
var params = { 
	content_type: 'audio/wav;rate=16000', 
	continuous: true, 
	'x-watson-learning-opt-out': true, 
	objectMode: true, 
	timestamps: true 
}; 
var recognizeStream = STT.recognizeUsingWebSocket(params); 

function onEvent(name, event) { console.log(name, JSON.stringify(event, null, 2)); }; 

function speechToText(){ 
// pipe in some audio fs.createReadStream('./sound16000.wav').pipe(recognizeStream) 
.on('data', function(event) { onEvent('Data:', event); }) 
.on('error', function(event) { onEvent('Error:', event); }) 
.on('readable', function(event) { onEvent('Readable:', event); }) 
.on('end', function(event) { onEvent('End:', event); }) 
.on('close', function(event) { onEvent('Close:', event); }); 
} 

speechToText();
```

My result is  
```
node .\speechToText.js 
Readable: undefined 
Close: 1006 
End: undefined 
```
but some audio can success. 
PS: The system is use ffmpeg to get audio from video. ffmpeg -i ./test_0.mp4 -y -ar 16000 -f wav ./test_0.wav

**Comment by JimZhang1028** [comment] 2019-01-10 13:21
This issue as the same as #202,Please confirm.

**Comment by dpopp07** [comment] 2019-01-15 21:48
@JimZhang1028 I think I have a solution for you. For this code to work now, you need to use the `interim_results` parameter. Add `interim_results: true,` to your parameters list and you will receive data back from the service. Please confirm this works with your application.

**Comment by JimZhang1028** [comment] 2019-01-16 07:48
@dpopp07 After added interim_results ，It works.
This interim_results parameter means we will get text for several times.
If we don't add this, we will get the whole text for one time.
Do you plan to find out why we don't use this parameter we can not get text?

**Comment by dpopp07** [comment] 2019-01-17 14:58
I'm glad that worked for you. I do plan to try and find that out but it will be difficult and I cannot guarantee it will be done soon. Closing this issue as the problem is solved, the other work will be tracked internally for now

**Closed by dpopp07** 2019-01-17 14:58 UTC
Labels: bug, support
