### ISSUE TITLE
option list of Watson Assistant

### ISSUE THREAD

**Issue by lee-zhg** [watson-developer-cloud/node-sdk#853] opened 2019-03-28 15:07 UTC
After created an instance of Watson Assistant with option list, it works fine while "Try it". However, the list does not show up while interacting with the instance in Node.js.

**Comment by dpopp07** [comment] 2019-04-12 18:19
@lee-zhg Will you include more information about your specific problem as well as list steps to reproduce?

**Comment by NeilSeligmann** [comment] 2019-07-02 21:33
I'm currently having the same issue.
Using the Assistant v1 when sending a message the output response does not include the "generic" child.

Example Input:
```
const response = await this.assistant.message({
    input: { text },
    workspace_id: this.bot.workspaceId,
    context
});
```

Example Output:
```
{
  "intents": [],
  "entities": [],
  "input": {
    "text": "test"
  },
  "output": {
    "text": [],
    "nodes_visited": [
      "node_1_1562102441312"
    ],
    "log_messages": []
  },
  "context": {
    "email": "test",
    "phoneNumber": 112234455,
    "conversation_id": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
    "system": {
      "initialized": true,
      "dialog_stack": [
        {
          "dialog_node": "root"
        }
      ],
      "dialog_turn_counter": 1,
      "dialog_request_counter": 1,
      "branch_exited": true,
      "branch_exited_reason": "completed"
    }
  }
}
```

Expected Output:
```
{
  "intents": [],
  "entities": [],
  "input": {
    "text": "test"
  },
  "output": {
    "text": [],
    "generic": [
      {
        "title": "WIII",
        "description": "asdadasd",
        "options": [
          {
            "label": "w1",
            "value": {
              "input": {
                "text": "1"
              }
            }
          },
          {
            "label": "w2",
            "value": {
              "input": {
                "text": "2"
              }
            }
          },
          {
            "label": "w3",
            "value": {
              "input": {
                "text": "3"
              }
            }
          }
        ],
        "response_type": "option"
      }
    ]
    "nodes_visited": [
      "node_1_1562102441312"
    ],
    "log_messages": []
  },
  "context": {
    "email": "test",
    "phoneNumber": 112234455,
    "conversation_id": "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee",
    "system": {
      "initialized": true,
      "dialog_stack": [
        {
          "dialog_node": "root"
        }
      ],
      "dialog_turn_counter": 1,
      "dialog_request_counter": 1,
      "branch_exited": true,
      "branch_exited_reason": "completed"
    }
  }
}
```

**Comment by NeilSeligmann** [comment] 2019-07-03 21:10
Solved it,
The problem was that we were using an old API version when creating the Assistant Instance.

**Before:**
```
this.assistant = new AssistantV1({
    iam_apikey: 'KEY',
    url: 'URL',
    version: '2018-02-19'
});
```

**Now:**
```
this.assistant = new AssistantV1({
    iam_apikey: 'KEY',
    url: 'URL',
    version: '2019-02-28'
});
```

**Comment by dpopp07** [comment] 2019-07-04 18:37
Thank you for posting that solution! Closing this issue as it seems to be resolved

@lee-zhg let me know if you are still having issues

**Closed by dpopp07** 2019-07-04 18:37 UTC
