### ISSUE TITLE
[speech-to-text] Adding Corpus code in Node.JS adds the filename as an OOV word

### ISSUE THREAD

**Issue by marconoel** [watson-developer-cloud/node-sdk#728] opened 2018-06-25 15:43 UTC
Using the following code 'as-is' below from the documentation : https://www.ibm.com/watson/developercloud/speech-to-text/api/v1/node.html?node#add-corpus

I create a corpora using a simple text file (attached below) and when I check the list of OOV, I see the filename of the text file added as an OOV, which should NOT happen.

--------------------
```js
const fs = require('fs')
var SpeechToTextV1 = require('watson-developer-cloud/speech-to-text/v1');

var speechToText = new SpeechToTextV1({
  username: '<username>',
  password: '<password>'
});

var addCorpusParams = {
  'customization_id': '<custom_id>',
  'corpus_file': fs.createReadStream('./data/IT-partial.txt'),
  'corpus_name': 'text_file',
  'allow_overwrite': 'true'
};

speechToText.addCorpus(addCorpusParams, function(error) {
  if (error) {
    console.log(error);
  } else {
    // Poll for corpus status.
  }
});
```

-----------------------
The corpus gets created correctly but when I check the OOV words, the filename gets added:
....
```json
{
      "display_as": "it-partial.txt",
      "sounds_like": [
        "it - partial txt"
      ],
      "count": 1,
      "source": [
        "text_file"
      ],
      "word": "it-partial.txt"
    }
```
.....

Using a "curl" command, I get the expected correct OOV list WITHOUT the filename (see curl command below)

```
curl -X POST -u "<username>":"<password>" --data-binary @./data/IT-partial.txt "https://stream.watsonplatform.net/speech-to-text/api/v1/customizations/<custom_id>/corpora/text_file?allow_overwrite=true"
```
[IT-partial.txt](https://github.com/watson-developer-cloud/node-sdk/files/2133751/IT-partial.txt)

**Comment by ammardodin** [comment] 2018-07-13 20:44
Interesting. I can recreate the issue as above. It seems that the service is picking up the `filename` from the request-style object and using it as an OOV. That seems odd to me.

@marconoel Can you try the following workaround and tell me if it works for you?

```javascript
var addCorpusParams = {
var addCorpusParams = {
  'customization_id': '<guid>',
  'corpus_file': {
    value: fs.createReadStream('./corpus_full.txt'),
    options: {
      filename: null,
      contentType: 'text/plain',
    }
  },
  'corpus_name': 'it_corpus',
  'allow_overwrite': 'true'
}
```

**Comment by germanattanasio** [comment] 2018-10-29 02:42
@mkistler I think the fix for this was released last week?

**Comment by mkistler** [comment] 2018-10-29 14:01
We should test to confirm the fix and then close if it works as intended.

**Comment by dpopp07** [comment] 2018-11-19 19:19
I cannot replicate the issue so I am assuming the fix was released

@marconoel if the issue persists for you, please let us know and we will re-open

**Closed by dpopp07** 2018-11-19 19:19 UTC
Labels: bug
