### ISSUE TITLE
[alchemy_language] pagination in concepts api

### ISSUE THREAD

**Issue by vondiplo** [watson-developer-cloud/node-sdk#286] opened 2016-07-24 19:02 UTC
**Steps to reproduce**
Requesting concepts with a maxRetrieve number greater than 50 returns maximum of only 50, doesn't provide any pagination to view next results.

**Expected behavior**
Returns the requested maxRetrieve number and if not returns an ability to paginate the results

**Actual behavior**
Only top 50 concepts are returned. No pagination .

**Node version**
Latest (^1.7.0)

**Comment by nfriedly** [comment] 2016-07-26 13:20
Hi @vondiplo, 

Can you give me an example URL that has > 50 concepts? Also, I don't know that pagination is supported by the API, but I'll double check on that.

**Comment by nfriedly** [comment] 2016-07-26 16:15
I just confirmed with the service team that both the maximum of 50 results and the lack of pagination are expected behavior. I relayed your message that both are desired features and I'm also looking into getting the current limitations documented better.

However, since this is not an issue with the SDK, I'm going to close this ticket for now.

**Closed by nfriedly** 2016-07-26 16:15 UTC
Labels: invalid
